### ISSUE TITLE
Application throws error Lib not found

### ISSUE THREAD

**Issue by mvofreire** [heresy/angularjs-social-login#1]
file://apis.google.com/js/platform.js Failed to load resource: net::ERR_FILE_NOT_FOUND

file://connect.facebook.net/en_US/sdk.js Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by kurapatijayaram** [comment]
This error occurs when you run it without using any local server. It is requesting the url with "file://" protocol instead of "http://"

**Comment by kurapatijayaram** [comment]
Let me remove that dependency.

**Comment by kurapatijayaram** [comment]
You can't use this plugin without local server .
