### ISSUE TITLE
This library only takes email, name and profile pic from the user, can tweak it to take more details ?

### ISSUE THREAD

**Issue by goelrohan6** [heresy/angularjs-social-login#10]

**Comment by kurapatijayaram** [comment]
Our intention is to make simple client side authentication plugin which requires basic details like name, email, profile pic.

**Comment by goelrohan6** [comment]
we can add something more to it and keep iit optional, would be helpful to many people !

**Comment by kurapatijayaram** [comment]
What are you looking for ??

**Comment by goelrohan6** [comment]
like getting more data from facebook, basic data like birthday, gender or anything that anyone might want and is available, would be optional of course, but for them who need it
