### ISSUE TITLE
Logout Directive for logout

### ISSUE THREAD

**Issue by Rupinderwadali** [heresy/angularjs-social-login#11]
Hello Developers,
I am Rupinderjit Kaur, I am trying to use the angularjs-social-login package in my application. Login authentication is working fine but I haven't find the directive for logout. As we have method for logout:
_socialLoginService.logout()_ For logout_
_$rootScope.$on('event:social-sign-out-success', function(event, logoutStatus){})_
But didn't find the directive in the documentation for logout. I am supposed to develop our own directive for logout? Please help me to figure this out.
Thanks:)

**Comment by kurapatijayaram** [comment]
There is no directive for logout.
