### ISSUE TITLE
Arrow syntax breaks compatibility with code not in ECMA6

### ISSUE THREAD

**Issue by gabs-simon** [heresy/angularjs-social-login#14]
On the latest changes, the facebook functions were altered and arrow syntax was used.
This change broke compatibility with my app, which is not on ECMAScript 6.

```
[16:26:44] [Uglify] Error in plugin 'gulp-uglify'
Message:
    C:\Users\gabsimon\PhpstormProjects\frontend\.tmp\serve\scripts\vendor-b30e8e582d.js: Unexpected token: operator (>)
Details:
    fileName: C:\Users\gabsimon\PhpstormProjects\frontend\.tmp\serve\scripts\vendor-b30e8e582d.js
    lineNumber: 89843
```

This error refer to the line `FB.getLoginStatus((response) => {`.

Is there a plan to revert this change, or add a build step in order to maintain compatilibity with ECMA5 code?

**Comment by kurapatijayaram** [comment]
Hi @gabriel-simonetti, Thanks for using our plugin. Regarding the issue, we don't have any plans to revert it. But I will push both versions (ECMA5 and ECMA6) in the next version of the package by this weekend. In the meanwhile try to use this plugin: https://www.npmjs.com/package/gulp-6to5

**Comment by kurapatijayaram** [comment]
Hi @gabriel-simonetti , we moved our package completely to ECMA5, use v2.5.1.
Thank you.
