### ISSUE TITLE
in which variable or element the return data is stored and how to access it

### ISSUE THREAD

**Issue by alihashir** [heresy/angularjs-social-login#15]
Hey Authors!
You  guys have done very good work... i appreciate your work much.
I am new to ngJs and i want to access the return data of all login process and store them in some variable and display them in table and also store info in database as well....
can you please brief me how can i do that ..
Please help me in easy way bcz i am new ...
Very thanks for your help.

**Comment by kurapatijayaram** [comment]
Thank you, Please check this: https://github.com/heresy/angularjs-social-login-example

**Comment by alihashir** [comment]
Very very very thanks to help me out.... I appreciate your work bro
