### ISSUE TITLE
missing semicolons

### ISSUE THREAD

**Issue by iwan-uschka** [heresy/angularjs-social-login#23]
please add a semicolon at line 127 and (at least) 218

after concatenating the libs i use, including your great plugin, the JS file isn't usable because the following lib doesn't start with a ";" and my app crashes

now i fix this kind of manually

thanks!

**Comment by rvtyagi** [comment]
Hi I face a similar issue, it shows an error in the console saying socialMedia.directive is not a function. Adding a semicolon to the end of your js fixes it. Please add it and commit to npm. The semicolon is required at line 218

**Comment by kurapatijayaram** [comment]
pull the latest code.
