### ISSUE TITLE
allow access window not asking

### ISSUE THREAD

**Issue by Surendra-04** [heresy/angularjs-social-login#26]
allow access window not asking for google and linkedin.

**Comment by Surendra-04** [comment]
pls help me ASAP

**Comment by kurapatijayaram** [comment]
Please mention your issue properly.

**Comment by Surendra-04** [comment]
i have integrated plugin to my project. i can login through gmail and linked also.but problem is we need ask allow  to access user email and etc data like  **# "Allow rightlink.org to do this?
By clicking Allow, you allow this app to use your information in accordance to their terms of service and privacy policies. You can remove this or any other app connected to your account in "**
i implemented same thing in php project in this link ..pls check gmail login in this project
https://rightlink.org/alumni/svpec/

**Comment by Surendra-04** [comment]
did u understand my problem?:(

**Comment by Surendra-04** [comment]
![ref](https://user-images.githubusercontent.com/30103928/29553982-26818676-873b-11e7-8252-6060ab5be9e0.png)

**Comment by Surendra-04** [comment]
its not asking as above image

**Comment by kurapatijayaram** [comment]
Any error in the console?

**Comment by Surendra-04** [comment]
no errors and logged in success fully..between that that should be ask as above image

**Comment by Surendra-04** [comment]
pls check that image...that is another project image..that window not asking in our plugin

**Comment by Surendra-04** [comment]
any confusion ?

**Comment by kpsrinivas** [comment]
This will be asked only once. It won't ask every time you login. Disable the app from the login used and it will be asked again. This is not an issue or bug. Closing this.

**Comment by Surendra-04** [comment]
For first time also its not asking for gmail?

**Comment by Surendra-04** [comment]
Pls check this url **http://qa.trustlogics.com/emdb/auth/login.**
Try to login with gmail and it will not asking you allowing window

**Comment by kpsrinivas** [comment]
It will be asked if you have set the permissions correct while registering the app in google's oauth section.

**Comment by kpsrinivas** [comment]
You are right. It did not ask me anything. Ensure you have followed all steps in google oauth setup. Else google won't return any user information.

**Comment by Surendra-04** [comment]
i have created  google+ api and gmail api in oauth console? where do i need to set that permissions? can u pls guide me? i am new for this

**Comment by Surendra-04** [comment]
![oauth](https://user-images.githubusercontent.com/30103928/29563378-e5bed10a-875a-11e7-9bb4-08ad0ce36358.png)

**Comment by kpsrinivas** [comment]
https://stackoverflow.com/questions/24442668/google-oauth-api-to-get-users-email-address

Looks like they have deprecated some - https://developers.google.com/+/web/api/rest/oauth

**Comment by kpsrinivas** [comment]
Are you asking for anything beyond basic profile ? If no, don't worry. It wont display the consent screen. Whenever you add an additional field, it will ask for the user consent.

**Comment by Surendra-04** [comment]
Yes i am asking basic email only for now

**Comment by Surendra-04** [comment]
but need to check it with other permissions also weather is showing or not..that is my intention

**Comment by Surendra-04** [comment]
and where do i need to set additional scope in our plugin? do you want me change directly in angularjs-social-login.js ?

**Comment by Surendra-04** [comment]
its working for me thanks a lot kpsrinivas..update scope and tested with 

scope: 'https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/plus.profile.emails.read'

**Comment by kpsrinivas** [comment]
Great!
