### ISSUE TITLE
FB is not defined

### ISSUE THREAD

**Issue by abhijeet9920** [heresy/angularjs-social-login#27]
I am using your package for my Facebook login app in angular. Included your script file and added dependencies, but I'm getting ReferenceError saying that FB is not defined on line number 196 in your script. Please help me where I'm doing wrong.
Thank you in advance

**Comment by abhijeet9920** [comment]
My mistake, app config is not set. Please ignore.

**Comment by dmjones** [comment]
@abhijeet9920 You can close your issue, to save others (like me) checking it before using the library.
