### ISSUE TITLE
How use socialLoginService.logout()

### ISSUE THREAD

**Issue by felipesudrj** [heresy/angularjs-social-login#3]
Someone help-me, I´m nob in angularJS, how use method socialLoginService.logout()?
@heresy or @kurapatijayaram

**Comment by kurapatijayaram** [comment]
Hi @felipesudrj , below is the example for logout.

angular.module('myApp', ['socialLogin']).controller('myCtrl', function($scope,socialLoginService) {
    $scope.signout = function(){
        socialLoginService.logout();
    }
});

**Comment by felipesudrj** [comment]
tks
