### ISSUE TITLE
event:social-sign-in-success is called multiple times

### ISSUE THREAD

**Issue by ycpatel813** [heresy/angularjs-social-login#5]
Hi, I have used this plugin and i am very happy with your work but when i use google + login it call two times. Why it happens i did not know but it will create two entry with same detail in database because I have used nodejs as backend which is asynchronous.

Please help. Thanks in advance.

**Comment by kurapatijayaram** [comment]
Hi, thanks for using our plugin. 
Regarding the issue, broadcast event 'social-sign-in-success' will trigger only once per click. At the back end you should be very careful while creating the records there should be some check while creating. For example if you are creating user records ? to eliminate duplicates make user email as primary key .

**Comment by ycpatel813** [comment]
Kurapatijayaram i have handled all things from backend side but it trigger two time simultaneously as fast as so two entry will create.

**Comment by kurapatijayaram** [comment]
Which DB you are using ??

**Comment by ycpatel813** [comment]
mongodb. broadcast will emit many time sir.

**Comment by ycpatel813** [comment]
Sir you can check out i have add console.log in  $rootScope.$on('event:social-sign-in-success') function.

**Comment by ycpatel813** [comment]
if you need video then i can create video for you to understand my code also.

**Comment by kurapatijayaram** [comment]
are you sure that you are triggering login button only once ?
Is it happening only for google ? or linkedIN also ?

**Comment by ycpatel813** [comment]
yes sure i am triggering google+ button only once. I will face this issue in google+ and facebook both.

**Comment by kurapatijayaram** [comment]
Let me check and get back to you soon.

**Comment by ycpatel813** [comment]
ok sir. Thank you.

**Comment by ankitvadariya** [comment]
@ycpatel813  you can solve by

user $scope.$on instated of $rootScope.$on

Source : http://stackoverflow.com/questions/19553598/angularjs-broadcast-repeating-execution-too-many-times

**Comment by kurapatijayaram** [comment]
Thanks @ankitvadariya , I don't know whether it solved @ycpatel813 issue ? if he is listening the event at more than once with $rootScope ? then the above solution should work.

**Comment by malaikoi** [comment]
I am having the same issue.
I am using facebook, linkedin and google login
$rootScope.$on('event:social-sign-in-success', function (event, user) {
register(data);
});
I had declared register function but it is called three times. After lot of effort i got the issue by commenting google and linkedin login.
That means number of login used in my html page that number of time register function is being called.
Any solution for this issue ?
