### ISSUE TITLE
FB accesstoken missing

### ISSUE THREAD

**Issue by pradyumnad** [heresy/angularjs-social-login#8]
Is there a specific reason for skipping accesstoken on FB login?

**Comment by kurapatijayaram** [comment]
Hi @pradyumnad , when I was writing this app I didn't found any information on how to fetch accessToken using SDK, but recently I found the method for that i.e "FB.getAuthResponse". Let me try and include that.

**Comment by pradyumnad** [comment]
@kurapatijayaram Accesstoken is present in the line 179 ```fbService.login().then(function(res){``` `res` object. You can include that. Thanks for considering my request. Cheers.
